// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type User struct {
	Username       string
	HashedPassword string
	Kills          int32
	Deaths         int32
	Wins           int32
	Losses         int32
	Draws          int32
	TimeAlive      int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
